#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>
#include "zmk-helpers/helper.h"

// layers
#define DEFAULT 0
#define L_NAV 1
#define L_NUM 2
#define L_SYM 3

#ifndef PASS
#define PASS &none
#endif
#ifndef PASS1
#define PASS1 &none
#endif
#ifndef PASS2
#define PASS2 &none
#endif
#ifndef PASS3
#define PASS3 &none
#endif

// Horizontal combos - left hand
// Should work fine, but some ansi-iso conflict forces to use the "grave"
// ZMK_COMBO(tilde, &kp NON_US_BSLH, 2 3, DEFAULT)
ZMK_COMBO(tilde, &kp GRAVE, 2 3, DEFAULT)

ZMK_COMBO(under, &kp UNDER, 22 23, DEFAULT)
//ZMK_COMBO(esc, &kp ESC, 26 27, DEFAULT)
ZMK_COMBO(tab, &kp TAB, 12 13, DEFAULT)

// Horizontal combos - right hand

// Those are geometrically natural, but it seems that DEL is pressed more easily,
// so I swapped them, BS is much more often neededed
//ZMK_COMBO(bspc, &kp BSPC, 19 20, DEFAULT)
//ZMK_COMBO(del, &kp DEL, 20 21, DEFAULT)
ZMK_COMBO(del, &kp DEL, 6 7, DEFAULT)
ZMK_COMBO(bspc, &kp BSPC, 7 8, DEFAULT)

ZMK_COMBO(lpar_lt, &mp_lpar_lt, 16 17, DEFAULT)
ZMK_COMBO(rpar_gt, &mp_rpar_gt, 17 18, DEFAULT)
ZMK_COMBO(lbrc_lbkt, &mp_lbrc_lbkt, 26 27, DEFAULT)
ZMK_COMBO(rbrc_rbkt, &mp_rbrc_rbkt, 27 28, DEFAULT)
ZMK_COMBO(pars, &mp_duo_par_ltgt, 16 17 18, DEFAULT)
ZMK_COMBO(bkts, &mp_duo_bkt, 26 27 28, DEFAULT)

// Vertical combos - left hand top row
ZMK_COMBO(excl, &kp EXCL, 0  10, DEFAULT)
ZMK_COMBO(at, &kp AT, 1 11, DEFAULT)
ZMK_COMBO(hash, &kp HASH, 2 12, DEFAULT)
ZMK_COMBO(dllr, &kp DLLR, 3 13, DEFAULT)
ZMK_COMBO(prcnt, &kp PRCNT, 4 14, DEFAULT)

// Vertical combos - left hand bottom row
ZMK_COMBO(grave, &kp GRAVE, 11 21, DEFAULT)
ZMK_COMBO(bslh, &kp BSLH, 12 22, DEFAULT)
ZMK_COMBO(equal, &kp EQUAL, 13 23, DEFAULT)

// Vertical combos - right hand top row
ZMK_COMBO(minus, &kp MINUS, 6 16, DEFAULT)
ZMK_COMBO(star, &kp STAR, 7 17, DEFAULT)
ZMK_COMBO(amps, &kp AMPS, 8 18, DEFAULT)

// Vertical combos - right hand bootom row
ZMK_COMBO(caret, &kp CARET, 15 25, DEFAULT)
ZMK_COMBO(plus, &kp PLUS, 16 26, DEFAULT)
ZMK_COMBO(fslh, &kp FSLH, 17 27, DEFAULT)
ZMK_COMBO(pipe, &kp PIPE, 18 28, DEFAULT)

/ {

    combos {
        compatible = "zmk,combos";

        combo_capsword {
            timeout-ms = <40>;
            key-positions = <32 33>;
            bindings = <&caps_word>;
            /* This ensures the combo is checked before the hold-tap logic matures */
            layers = <0>;
        };

        combo_sticky_shift {
            timeout-ms = <40>;
            key-positions = <31 34>;
            bindings = <&skq LSHIFT>;
            layers = <0>;
        };
    };

    macros {
        macro_duo_kp: macro_duo_kp {
            compatible = "zmk,behavior-macro-two-param";
            #binding-cells = <2>;
            bindings = <&macro_param_1to1> , <&macro_tap &kp MACRO_PLACEHOLDER>
                     , <&macro_param_2to1> , <&macro_tap &kp MACRO_PLACEHOLDER>;
        };

        // A hack to make the ; (Shift-,) work. It doesn't work perfectly
        // (Shift- and continuout taps of , produce ;,,,,), but acceptable.
        semi_clean: semi_clean {
            compatible = "zmk,behavior-macro";
            #binding-cells = <0>;
            wait-ms = <10>;
            tap-ms = <10>;
            bindings
            = <&macro_release &kp LSHFT &kp RSHFT>
            , <&macro_press &kp SEMI>
            , <&macro_pause_for_release>
            , <&macro_release &kp SEMI>
            ;
        };

    };

    behaviors {

        // tap:     {}
        // shift:   []
        mp_duo_bkt: morph_duo_bkt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&macro_duo_kp LBRC RBRC>, <&macro_duo_kp LBKT RBKT>;
        };

        // tap:     ()
        // shift:   <>
        mp_duo_par_ltgt: morph_duo_par_ltgt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&macro_duo_kp LPAR RPAR>, <&macro_duo_kp LT GT>;
        };

        // tap:     {
        // shift:   [
        mp_lbrc_lbkt: morph_lbrc_lbkt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp LBRC>, <&kp LBKT>;
        };

        // tap:     }
        // shift:   ]
        mp_rbrc_rbkt: morph_rbrc_rbkt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp RBRC>, <&kp RBKT>;
        };

        // tap:     (
        // shift:   <
        mp_lpar_lt: morph_lpar_lt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp LPAR>, <&kp LT>;
        };

        // tap:     )
        // shift:   >
        mp_rpar_gt: morph_rpar_gt {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp RPAR>, <&kp GT>;
        };

        // tap:     ,
        // shift:   ;
        /* this is ok in the clean OS, but conflicts with Karabiner
        mp_key_cs: morph_key_comma_semi {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp COMMA>, <&kp SEMICOLON>;
        };
        */
        mp_key_cs: morph_key_comma_semi {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp COMMA>, <&semi_clean>; // Använd makrot för Shift-lagret
        };

        // tap:     .
        // shift:   :
        /* This would work if not the Karabiner
        mp_key_dc: morph_key_dot_colon {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            bindings = <&kp DOT>, <&kp COLON>;
        };
        */
        mp_key_dc: morph_key_dot_colon {
            compatible = "zmk,behavior-mod-morph";
            #binding-cells = <0>;
            bindings = <&kp DOT>, <&kp SEMI>;
            mods = <(MOD_LSFT|MOD_RSFT)>;
            keep-mods = <(MOD_LSFT|MOD_RSFT)>; // Colon is Shift-semicolon, so we must keep Shifts
        };

        hml: home_row_mod_left {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            require-prior-idle-ms = <150>;
            tapping-term-ms = <280>;
            quick-tap-ms = <175>;
            bindings = <&kp>, <&kp>;
            hold-trigger-key-positions = < 5 6 7 8 9   15 16 17 18 19    25 26 27 28 29    33 34 35>;
            hold-trigger-on-release;
        };
        hmr: home_row_mod_right {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            require-prior-idle-ms = <150>;
            tapping-term-ms = <280>;
            quick-tap-ms = <175>;
            bindings = <&kp>, <&kp>;
            hold-trigger-key-positions = < 0 1 2 3 4    10 11 12 13 14    20 21 22 23 24    30 31 32>;
            hold-trigger-on-release;
        };
        hmr_morph_cs: hmr_morph_comma_semi {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            require-prior-idle-ms = <150>;
            tapping-term-ms = <280>;
            quick-tap-ms = <175>;
            /* This is the magic change: the second binding is a behavior, not &kp */
            bindings = <&kp>, <&mp_key_cs>;
            hold-trigger-key-positions = < 0 1 2 3 4   10 11 12 13 14   20 21 22 23 24   30 31 32>;
            hold-trigger-on-release;
        };
        hmr_morph_dc: hmr_morph_dot_colon {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            require-prior-idle-ms = <150>;
            tapping-term-ms = <280>;
            quick-tap-ms = <175>;
            /* This is the magic change: the second binding is a behavior, not &kp */
            bindings = <&kp>, <&mp_key_dc>;
            hold-trigger-key-positions = < 0 1 2 3 4   10 11 12 13 14   20 21 22 23 24   30 31 32>;
            hold-trigger-on-release;
        };

        skq: sticky_key_quick_release {
            compatible = "zmk,behavior-sticky-key";
            #binding-cells = <1>;
            bindings = <&kp>;
            release-after-ms = <1000>;
            quick-release;
            ignore-modifiers;
        };
        dsk: dual_sticky_key {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "balanced";
            require-prior-idle-ms = <150>;
            tapping-term-ms = <280>;
            quick-tap-ms = <175>;
            bindings = <&kp>, <&skq>;
            hold-trigger-on-release;
        };

    };

    keymap {
        compatible = "zmk,keymap";

        default_layer {
            bindings = <
&kp Q  &kp W  &kp E  &kp R  &kp T                                       &kp Y  &kp U   &kp I     &kp O   &kp P
&hml LGUI A  &hml LALT S &hml LCTRL D  &hml LSHIFT F  &kp G             &kp H  &hmr RSHIFT J   &hmr RCTRL K           &hmr LALT L           &hmr RGUI APOS
&hml LGUI Z  &hml LALT X &hml LCTRL C  &hml LSHIFT V  &kp B             &kp N  &hmr RSHIFT M   &hmr_morph_cs RCTRL 0  &hmr_morph_dc LALT 0  &hmr RGUI FSLH
                 &mt LSHIFT F13 &mt LGUI RET &lt L_NUM ESC              &lt L_NAV TAB &lt L_SYM SPACE &mt RSHIFT F14
            >;
        };

        nav_layer {
            bindings = <
&kp Q          &kp W         &kp E          &kp R          &kp T              &kp K_REDO     PASS1         PASS2        PASS3      &bootloader
&hml LGUI A    &hml LALT S   &hml LCTRL D   &hml LSHIFT F  &kp G              &kp LEFT       &kp DOWN      &kp UP        &kp RIGHT   &caps_word
&kp Z          &kp X         &kp C          &kp V          &kp B              &kp HOME       &kp PG_DN     &kp PG_UP     &kp END     &kp INS
                             &kp C          PASS           &none              &kp RET        &kp BSPC      &kp DEL
            >;
        };

        num_layer {
            bindings = <
&bootloader &kp N7     &kp N8      &kp N9       &kp RBKT            &kp Y  &kp U   &kp I    &kp O   &kp P
&kp LT      &kp N4     &kp N5      &kp N6       &kp EQUAL           &kp H  &kp J   &kp K    &kp L   &kp N0
&kp GRAVE   &kp N1     &kp N2      &kp N3       &kp N0              &kp N  &kp M   &kp COMMA &kp DOT &kp FSLH
                                           &kp DOT      &kp N0      &kp MINUS  &kp RET &none &kp DEL
            >;
        };

        sym_layer {
            bindings = <
&kp LBRC   &kp LA(W)  &kp LA(E)   &kp LA(R)    &kp RBRC             &kp Y  &kp U   &kp I     &kp O   &bootloader
&kp LA(A)  &kp LA(S)  &kp LA(D)   &kp LA(F)    &kp RBRC             &kp H  &kp J   &kp K     &kp L   &kp N0
&kp TILDE  &kp EXCL   &kp AT_SIGN &kp HASH     &kp PIPE             &kp N  &kp M   &kp COMMA &kp DOT &kp FSLH
                      &kp LPAR    &kp RPAR     &kp UNDER            &none &kp BSPC &kp DEL
            >;
        };

    };
};
